/** Curated educational cards shared by UI and server. No client-authored advice reaches the provider. */
export const COACHING_CARDS = {
 'pullup-return-together':{exercise:'pullup',observation:'In the linked return, your shoulders and hips come down together while your visible hand stays in a similar position.',cue:'Keep your hips and shoulders coming down together on your next comfortable attempt.',why:'A coordinated return gives you a more repeatable starting point for the next pull. This describes the linked return only, not a complete rep or a shoulder-safety verdict.',sourceKey:'ace-pullup'},
 'pushup-forearm-support':{exercise:'pushup',observation:'Your hand stays in a similar image position while the visible forearm moves in the marked section.',cue:'If this matches the push-up movement you intended, keep that hand position steady as you move.',why:'This gives you one visible part of the movement to keep consistent. It does not establish hand pressure, shoulder position or a completed rep.',sourceKey:'ace-pushup'},
 'pullup-forearm-support':{exercise:'pullup',observation:'Your hand stays in a similar image position while the visible forearm moves in the marked section.',cue:'If this matches the pull-up movement you intended, keep that hand position steady as you move.',why:'This gives you one visible part of the movement to keep consistent. It does not establish grip pressure, shoulder position or a completed rep.',sourceKey:'ace-pullup'},
 'squat-shin-support':{exercise:'squat',observation:'Your ankle stays in a similar image position while the visible shin moves in the marked section.',cue:'If this matches the squat movement you intended, aim for a steady base as you move.',why:'This gives you one visible part of the movement to keep consistent. It does not establish foot pressure, hip position or a completed rep.',sourceKey:'ace-squat'},
 "pushup-arm-tempo":{"exercise":"pushup","observation":"The local review marked a timing difference in the visible arm movement.","cue":"If you want a steadier pace, give the lowering part a little more time before coming back up.","why":"A deliberate pace gives you one part of the movement to practise and repeat. Different tempos can be intentional; faster does not automatically mean wrong.","sourceKey":"ace-pushup"},
 "pushup-arm-rhythm":{"exercise":"pushup","observation":"The local review marked similar timing across two visible arm movements. This is one visible strength, not a whole-form verdict.","cue":"Keep that repeatable rhythm when it fits the pace you are practising.","why":"A repeatable pace makes it easier to notice a change on your next attempt. The two phases do not need to have equal speed.","sourceKey":"ace-pushup"},
 "pushup-forearm-tempo":{"exercise":"pushup","observation":"The local review marked a quicker return of the visible forearm. Hidden joints were not used.","cue":"If you want a steadier pace, try giving that return a little more time.","why":"A deliberate return gives you a pace you can practise and repeat. A faster return may also be intentional.","sourceKey":"ace-pushup"},
 "pushup-forearm-rhythm":{"exercise":"pushup","observation":"The local review marked two similar visible forearm paths. This does not establish the hidden parts of your form.","cue":"Keep that repeatable movement when it fits the exercise and pace you are practising.","why":"A repeatable visible path gives you one part of the movement to compare next time. It does not require equal speeds in both directions.","sourceKey":"ace-pushup"},
 "pullup-arm-tempo":{"exercise":"pullup","observation":"The local review marked a timing difference in the visible arm movement.","cue":"If you are practising controlled pull-ups, give the lowering part a little more time.","why":"A deliberate pace gives you one part of the movement to practise and repeat. Different tempos can be intentional; faster does not automatically mean wrong.","sourceKey":"ace-pullup"},
 "pullup-arm-rhythm":{"exercise":"pullup","observation":"The local review marked similar timing across two visible arm movements. This is one visible strength, not a whole-form verdict.","cue":"Keep that repeatable rhythm when it fits the pace you are practising.","why":"A repeatable pace makes it easier to notice a change on your next attempt. The two phases do not need to have equal speed.","sourceKey":"ace-pullup"},
 "pullup-forearm-tempo":{"exercise":"pullup","observation":"The local review marked a quicker return of the visible forearm. Hidden joints were not used.","cue":"If you want a steadier pace, try giving that return a little more time.","why":"A deliberate return gives you a pace you can practise and repeat. A faster return may also be intentional.","sourceKey":"ace-pullup"},
 "pullup-forearm-rhythm":{"exercise":"pullup","observation":"The local review marked two similar visible forearm paths. This does not establish the hidden parts of your form.","cue":"Keep that repeatable movement when it fits the exercise and pace you are practising.","why":"A repeatable visible path gives you one part of the movement to compare next time. It does not require equal speeds in both directions.","sourceKey":"ace-pullup"},
 "squat-leg-tempo":{"exercise":"squat","observation":"The local review marked a timing difference in the visible leg movement.","cue":"If you want a steadier pace, give the lowering part a little more time before coming back up.","why":"A deliberate pace gives you one part of the movement to practise and repeat. Different tempos can be intentional; faster does not automatically mean wrong.","sourceKey":"ace-squat"},
 "squat-leg-rhythm":{"exercise":"squat","observation":"The local review marked similar timing across two visible leg movements. This is one visible strength, not a whole-form verdict.","cue":"Keep that repeatable rhythm when it fits the pace you are practising.","why":"A repeatable pace makes it easier to notice a change on your next attempt. The two phases do not need to have equal speed.","sourceKey":"ace-squat"},
 "squat-shin-tempo":{"exercise":"squat","observation":"The local review marked a quicker return of the visible shin. Hidden joints were not used.","cue":"If you want a steadier pace, try giving that return a little more time.","why":"A deliberate return gives you a pace you can practise and repeat. A faster return may also be intentional.","sourceKey":"ace-squat"},
 "squat-shin-rhythm":{"exercise":"squat","observation":"The local review marked two similar visible shin paths. This does not establish the hidden parts of your form.","cue":"Keep that repeatable movement when it fits the exercise and pace you are practising.","why":"A repeatable visible path gives you one part of the movement to compare next time. It does not require equal speeds in both directions.","sourceKey":"ace-squat"},
 "pushup-together":{"exercise":"pushup","observation":"The local review marked hips and shoulders mostly moving in the same direction in this section.","cue":"Keep that togetherness as you repeat the movement.","why":"Moving together makes the next rep easier to coordinate and repeat. This is one visible strength, not an all-clear on the whole set.","sourceKey":"ace-pushup"},
 "squat-together":{"exercise":"squat","observation":"The local review marked hips and shoulders mostly moving in the same direction in this section.","cue":"Keep that togetherness as you repeat the movement.","why":"Moving together makes the next rep easier to coordinate and repeat. This is one visible strength, not an all-clear on the whole set.","sourceKey":"ace-squat"},
 'pushup-timing':{exercise:'pushup',observation:'Your local review marked hips and shoulders moving out of sync. Replay that section to check the tracking.',cue:'Try a slower rep with your hips and chest moving down and back up together. If a full push-up is hard to control without pain, use an easier version you can control.',why:'Moving as one unit helps keep the rep steady instead of bending in the middle of the press.',sourceKey:'ace-pushup'},
 'pushup-hip-position':{exercise:'pushup',observation:'Your local review marked a section where the hips appeared lower than the shoulder-to-ankle line. Camera perspective can change that appearance.',cue:'Check the replay, then aim to keep your hips in line with the rest of your body through a comfortable rep.',why:'Keeping the body line steady helps you practice the same movement throughout the press.',sourceKey:'ace-pushup'},
 'squat-timing':{exercise:'squat',observation:'Your local review marked hips and chest moving out of sync. Check that the tracking stays on your body.',cue:'Try a slower squat and bring your hips and chest back up together.',why:'Rising together makes the ascent one coordinated movement, rather than starting with the hips and then catching up with the chest.',sourceKey:'ace-squat'},
 'pullup-swing':{exercise:'pullup',observation:'Your local review marked back-and-forth movement relative to the hands. This is a camera-view observation.',cue:'If you are aiming for strict pull-ups, let the swing settle before the next rep.',why:'A still start makes a strict pull-up more repeatable instead of relying on momentum. Intentional momentum-based variations are different.',sourceKey:'ace-pullup'},
 'pullup-descent':{exercise:'pullup',observation:'Your local review marked a lowering phase that took less time than the upward phase. Speed alone does not prove lost control.',cue:'Give the lowering part a little more time and keep the movement steady.',why:'It gives you a chance to practice controlling the return instead of rushing into the next rep.',sourceKey:'ace-pullup'},
 'practice-pushup':{exercise:'pushup',observation:'This is a general practice cue, not a fault detected in the recording.',cue:'Aim to move your hips and chest together through the rep, in a version you can control comfortably.',why:'That helps the press stay steady instead of letting the body fold in the middle.',sourceKey:'ace-pushup'},
 'practice-pullup':{exercise:'pullup',observation:'This is a general practice cue, not a fault detected in the recording.',cue:'For a strict pull-up, start without a swing and give the lowering part time.',why:'A repeatable start and return make it easier to practice controlled movement.',sourceKey:'ace-pullup'},
 'practice-squat':{exercise:'squat',observation:'This is a general practice cue, not a fault detected in the recording.',cue:'Lower steadily and bring your hips and chest back up together, within a comfortable range.',why:'The goal is one coordinated movement you can repeat, not forcing a particular depth.',sourceKey:'ace-squat'},
} as const;
export function trustedCoachingCard(exercise:string,id:string){
 if(!Object.hasOwn(COACHING_CARDS,id))return null;
 const card=COACHING_CARDS[id as keyof typeof COACHING_CARDS];
 return card.exercise===exercise?{id,...card}:null;
}
