/** Curated educational cards shared by UI and server. No client-authored advice reaches the provider. */
export const COACHING_CARDS = {
 'pushup-timing':{exercise:'pushup',observation:'Your local review marked hips and shoulders moving out of sync. Replay that section to check the tracking.',cue:'Try a slower rep with your hips and chest moving down and back up together. If a full push-up is hard to control without pain, use an easier version you can control.',why:'Moving as one unit helps keep the rep steady instead of bending in the middle of the press.',sourceKey:'ace-pushup'},
 'pushup-hip-position':{exercise:'pushup',observation:'Your local review marked a section where the hips appeared lower than the shoulder-to-ankle line. Camera perspective can change that appearance.',cue:'Check the replay, then aim to keep your hips in line with the rest of your body through a comfortable rep.',why:'Keeping the body line steady helps you practice the same movement throughout the press.',sourceKey:'ace-pushup'},
 'squat-timing':{exercise:'squat',observation:'Your local review marked hips and chest moving out of sync. Check that the tracking stays on your body.',cue:'Try a slower squat and bring your hips and chest back up together.',why:'Rising together makes the ascent one coordinated movement, rather than starting with the hips and then catching up with the chest.',sourceKey:'ace-squat'},
 'pullup-swing':{exercise:'pullup',observation:'Your local review marked back-and-forth movement relative to the hands. This is a camera-view observation.',cue:'If you are aiming for strict pull-ups, let the swing settle before the next rep.',why:'A still start makes a strict pull-up more repeatable instead of relying on momentum. Intentional momentum-based variations are different.',sourceKey:'ace-pullup'},
 'pullup-descent':{exercise:'pullup',observation:'Your local review marked a lowering phase that took less time than the upward phase. Speed alone does not prove lost control.',cue:'Give the lowering part a little more time and keep the movement steady.',why:'It gives you a chance to practice controlling the return instead of rushing into the next rep.',sourceKey:'ace-pullup'},
 'practice-pushup':{exercise:'pushup',observation:'This is a general practice cue, not a fault detected in the recording.',cue:'Aim to move your hips and chest together through the rep, in a version you can control comfortably.',why:'That helps the press stay steady instead of letting the body fold in the middle.',sourceKey:'ace-pushup'},
 'practice-pullup':{exercise:'pullup',observation:'This is a general practice cue, not a fault detected in the recording.',cue:'For a strict pull-up, start without a swing and give the lowering part time.',why:'A repeatable start and return make it easier to practice controlled movement.',sourceKey:'ace-pullup'},
 'practice-squat':{exercise:'squat',observation:'This is a general practice cue, not a fault detected in the recording.',cue:'Lower steadily and bring your hips and chest back up together, within a comfortable range.',why:'The goal is one coordinated movement you can repeat, not forcing a particular depth.',sourceKey:'ace-squat'},
} as const;
export function trustedCoachingCard(exercise:string,id:string){
 if(!Object.hasOwn(COACHING_CARDS,id))return null;
 const card=COACHING_CARDS[id as keyof typeof COACHING_CARDS];
 return card.exercise===exercise?{id,...card}:null;
}
